### ISSUE TITLE
Odd icon for Rakefiles

### ISSUE THREAD

**Issue by Alhadis** [donovanhiland/atom-file-icons#1]
Hey there,

I'm wondering where the choice of icon for Rakefiles came from. Was it [sourced from this](http://www.rubyrake.org/about-us/)?

<img align="center" hspace="20" src="http://www.rubyrake.org/wp-content/uploads/2016/09/logo-ruby.png" alt="Ruby Rake logo" valign="middle" /> <img align="center" src="https://cloud.githubusercontent.com/assets/2346707/22421573/f36a8e58-e73b-11e6-8862-25cc498d41c2.png" width="128" alt="Rakefile icon" valign="middle" />

If so, that page's description would suggest it's not at all connected with Ruby:

> **Ruby Rake Software** is the creation of an experienced master of software industry Mr. Rake. The software guru holds a double Masters in Engineering and Computer Sciences with certified courses in software from top universities of the world…

The icon in particular even seems like a stock logo, going by a [reverse image search](https://www.google.com/searchbyimage?&image_url=https://cloud.githubusercontent.com/assets/2346707/22421573/f36a8e58-e73b-11e6-8862-25cc498d41c2.png).

To the best of my current knowledge, Rake doesn't have a logo.

**Comment by donovanhiland** [comment]
You're right. Rake doesn't have a logo from what I could find. This package was meant to mirror an icon pack I used in Visual Studio Code (https://github.com/vscode-icons/vscode-icons). That's the icon they use. I'm open for any suggestions.

**Comment by Alhadis** [comment]
Ah. Guess I should bring this up over there, then.

> I'm open for any suggestions.

I'd just stick to Ruby's usual icon, to be honest. There are other [filenames](https://github.com/file-icons/atom/blob/master/config.cson#L2997) used in Ruby which have a similar construction: `Gemfile`, `Buildfile`, `Berksfile`, `Guardfile`, `Jarfile`... the list goes on. Wouldn't really make sense for Rakefile to be treated differently.

**Comment by donovanhiland** [comment]
Makes more sense and looks good. Nice catch.

**Comment by JimiC** [comment]
@donovanhiland The icon association has been done deliberately, exactly because `Rakefile` doesn't have a logo and we wanted to differentiate the build script from the rest of the `Ruby` files.

**Comment by Alhadis** [comment]
Understood. I had a similar experience with the [GN build system](https://www.chromium.org/developers/gn-build-configuration). I didn't want to use Atom's generic "todo" icon, so I [made an icon up](https://github.com/file-icons/source/blob/master/svg/GN.svg) instead.

GN stands for "Generate Ninja", referring to the [underlying build engine](https://ninja-build.org/) named Ninja. You can see why I wanted something distinctive. =)
