### ISSUE TITLE
Default folder and default file icons don't show up when using the One Dark theme

### ISSUE THREAD

**Issue by ghost** [donovanhiland/atom-file-icons#4]
System:
- Windows 8.1 x64
- Atom v1.16.0 (stable)
- One Dark theme v1.9.2

Issue:
The file icons for the folder and empty file(file without any file extension) do not show up in the tree view pane when using **One Dark** theme

![image](https://cloud.githubusercontent.com/assets/11004631/25157664/5cda6b58-24c0-11e7-84dc-24fec58234c7.png)

Now the same thing but with **Atom Dark** theme:

![image](https://cloud.githubusercontent.com/assets/11004631/25157675/6fcaa890-24c0-11e7-90a4-6521e3902720.png)

Similarly it works with Seti UI as well

![image](https://cloud.githubusercontent.com/assets/11004631/25157689/81e7a4a6-24c0-11e7-81a2-f2ab24826a3d.png)

However the opened/expanded folder icon works:

![image](https://cloud.githubusercontent.com/assets/11004631/25157644/45c41072-24c0-11e7-8f70-80b02d6f8c28.png)

No other custom icons package is installed so I don't feel any other icon package is causing the issue. My best guess is some conflict is happening between what One dark has prescribed as the folder icon and that of atom-file-icons.

Side Note: The 1 depreciation you see in the bottom right, is a reference to the atom-editor background-color which I set as black, not related to the file icon issue itself.

**Comment by donovanhiland** [comment]
This should be fixed in 57d66aa5b539df79a2025a8a523dbe7cf3477801.

**Comment by donovanhiland** [comment]
Let me know if you come across anything else related to the theme.

**Comment by ghost** [comment]
Hi, it works now, however the positioning is slightly off

![image](https://cloud.githubusercontent.com/assets/11004631/25294308/320fa4ea-26fc-11e7-9378-a103fff5048f.png)

If you observe the top left corner, the closed folder icon is slightly raised above the proper position

![image](https://cloud.githubusercontent.com/assets/11004631/25294367/7308d0f2-26fc-11e7-9b87-4f55dc4d62b3.png)

Same thing for the empty file icon in the list tree view. It's not really an issue I guess but other than that everything is working perfectly, just need to adjust the positioning. 

And once again its only with this theme, in Atom Dark/Light theme it works without a hitch, position is perfect.
