### ISSUE TITLE
Add more patterns for other types of shell scripts

### ISSUE THREAD

**Issue by Jeff-Walker** [donovanhiland/atom-file-icons#7]
A good list to add would be:

- *.ksh, .kshrc
- *.bash, .bashrc, .bash_profile, .bash_logout, .inputrc
- *.zsh, .zshrc, *.zfunc, .zprofile, .zshenv, .zlogin, .zlogout
- *.csh, *.tcsh, .cshrc, .tcshrc
- .profile, .login, .logout

They can all use the same *.sh icon.

**Comment by donovanhiland** [comment]
If I have some time this weekend I might look into this. If not I'd be happy and open to a PR adding these

**Comment by donovanhiland** [comment]
Disregard the above comment. Thanks for the PR
