### ISSUE TITLE
No icon for a 'c/c++' source file

### ISSUE THREAD

**Issue by aveepsit** [donovanhiland/atom-file-icons#9]
It would be helpful if you could add support for the C/C++ files

**Comment by donovanhiland** [comment]
If I have some time this weekend I might look into this. If not I'd be happy and open to a PR adding these

**Comment by aveepsit** [comment]
Hello, @donovanhiland  I have given a try at adding icons for c & c++. 
This is my first contribution to Open Source, If there is something wrong please do notify me. I'll try my best at rectifying it, as best I can.

**Comment by donovanhiland** [comment]
Closed by #10
